# Generated by Django 3.2.7 on 2021-11-07 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='notation',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='task',
        ),
        migrations.RemoveField(
            model_name='notation',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notation',
            name='task',
        ),
        migrations.RemoveField(
            model_name='track',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='track',
            name='task',
        ),
        migrations.CreateModel(
            name='TrackTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task')),
                ('track', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.notation')),
                ('track', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.track')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.notation')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
        migrations.CreateModel(
            name='NotationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.notation')),
                ('notification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.notification')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.calendar')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.calendar')),
                ('notification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.notification')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.calendar')),
                ('notation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.notation')),
            ],
        ),
    ]
