# Generated by Django 3.2.7 on 2021-11-25 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211107_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheettask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timesheettask',
            name='timesheet',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TaskNotation',
        ),
        migrations.DeleteModel(
            name='TimesheetTask',
        ),
    ]
