# Generated by Django 3.2.7 on 2021-12-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
