# Generated by Django 4.0.2 on 2022-02-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_calendar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='tasks',
            field=models.ManyToManyField(to='api.Task'),
        ),
        migrations.DeleteModel(
            name='TrackTask',
        ),
    ]
