# Generated by Django 4.0.2 on 2022-02-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_track_tasks_delete_tracktask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='tasks',
        ),
        migrations.AddField(
            model_name='track',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
    ]
