# Generated by Django 4.0.2 on 2022-02-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_track_tasks_track_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarnotification',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='calendarnotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='calendartask',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='calendartask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='notation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notationnotification',
            name='notation',
        ),
        migrations.RemoveField(
            model_name='notationnotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='tracknotation',
            name='notation',
        ),
        migrations.RemoveField(
            model_name='tracknotation',
            name='track',
        ),
        migrations.AddField(
            model_name='calendar',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
        migrations.DeleteModel(
            name='CalendarNotation',
        ),
        migrations.DeleteModel(
            name='CalendarNotification',
        ),
        migrations.DeleteModel(
            name='CalendarTask',
        ),
        migrations.DeleteModel(
            name='Notation',
        ),
        migrations.DeleteModel(
            name='NotationNotification',
        ),
        migrations.DeleteModel(
            name='TrackNotation',
        ),
    ]
