# Generated by Django 4.0.2 on 2022-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_calendar_task_alter_calendar_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
